name: py2
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - python==2.7.13
  - scipy==0.19.0
  - numpy==1.13.1
  - pandas==0.20.3
  - matplotlib
  - jupyter==1.0.0
  - scikit-learn==0.18.1
  - pip:
    - opencv_python==3.3.0.10
    - seaborn==0.8.1
    - pillow==4.3.0
    - tqdm